### ISSUE TITLE
Update venue information for Fall 2016

### ISSUE THREAD

**Issue by joethe** [UMM-CSci/lanparty#2]
The Fall 2016 venue is Oyate.
Since many of the attendees are anticipated to be incoming students, it might be prudent
to include extra information about where Oyate is and how to get into the building.

**Comment by harre096** [comment]
Can we be lazy and just link the work Oyate to the UMM page? https://www.morris.umn.edu/conferencesspecialevents/venues/oyate/

**Comment by joethe** [comment]
Yeah, that'd probably work just fine.
